# Generated by Django 5.2.1 on 2025-07-26 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 25, 19, 48, 49, 911323, tzinfo=datetime.timezone.utc)),
        ),
    ]
