# Generated by Django 5.2.1 on 2025-07-27 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usersubscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
