# Generated by Django 5.2.1 on 2025-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_photo_favorites_photo_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='photo', to='core.comment'),
        ),
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.comment'),
        ),
    ]
