# Generated by Django 5.2.1 on 2025-08-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_photo_comments_video_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AddField(
            model_name='photo',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
    ]
