# Generated by Django 5.2.1 on 2025-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_photo_is_featured_photo_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': "Plan d'abonnement", 'verbose_name_plural': "Plans d'abonnement"},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si ce plan est disponible à la souscription.', verbose_name='Plan actif'),
        ),
    ]
