# Generated by Django 5.2.1 on 2025-08-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('uploading', "En cours d'upload"), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('uploaded_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('upload_speed', models.FloatField(default=0.0)),
                ('time_remaining', models.PositiveIntegerField(default=0)),
                ('time_elapsed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='core.video')),
            ],
        ),
    ]
