# Generated by Django 5.2.1 on 2025-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_video_file_key_video_video_url_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/gallery/'),
        ),
    ]
