# Generated by Django 4.2.11 on 2025-09-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_photo_file_key_photo_image_url_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée de la vidéo en secondes', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Contenu premium'),
        ),
        migrations.AddField(
            model_name='video',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='Année de sortie de la vidéo', null=True),
        ),
    ]