# Generated by Django 5.2.1 on 2025-09-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_video_duration_video_is_premium_video_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover_film',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
    ]
