# Generated by Django 5.2.1 on 2025-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_video_cover_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Plan actif'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
